# Runs conventional commit check on PR
name: Checks
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  checks:
    name: Checks, builds and tests code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Lint Code
        run: pnpm lint:all
      - name: Lint CSS
        run: pnpm lint:style
      - name: Tests
        run: pnpm test
