import Head from 'next/head';
import { Inter } from 'next/font/google';
import React from 'react';
import { Button } from '@digdir/design-system-react';

const inter = Inter({ subsets: ['latin'] });

import { Footer } from '@/components/Footer/Footer';

import '@altinn/figma-design-tokens/dist/tokens.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next Appd</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <main className={`${inter.className}`}>
        <h2>Next.js app</h2>
        <h3>Her er ein knapp frå designsystemet</h3>
        <Button size='medium'>Click here</Button>
      </main>
      <Footer />
    </>
  );
}
