import Head from 'next/head';
import { Inter } from 'next/font/google';
import React from 'react';
import { Button } from '@digdir/design-system-react';
import { useTranslation } from 'react-i18next';
import { useDispatch, useSelector } from 'react-redux';

import { Footer } from '@/components/Footer/Footer';

import { useAppSelector } from '../store/hooks';

import { changeLanguage } from './../i18n';

const inter = Inter({ subsets: ['latin'] });

import '@altinn/figma-design-tokens/dist/tokens.css';

export default function Home() {
  const { t } = useTranslation(['main']);
  const activePage = useAppSelector((state) => state.activePage);

  const onClickLanguageChange = (
    e:
      | React.ChangeEvent<HTMLSelectElement>
      | React.MouseEvent<HTMLButtonElement>,
  ) => {
    if (typeof e.currentTarget.value === 'string') {
      changeLanguage(e.currentTarget.value);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next Appd</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <main className={`${inter.className}`}>
        <h2>{activePage.content.node.title}</h2>
        <h3>Her er ein knapp frå designsystemet</h3>
        <Button
          size='medium'
          value='en'
          onClick={onClickLanguageChange}
        >
          Click here
        </Button>
        <select
          className='custom-select'
          style={{ width: 200 }}
          onChange={onClickLanguageChange}
        >
          <option value='nb'>Norsk</option>
          <option value='en'>English</option>
          <option value='sa'>sámegiella</option>
        </select>

        <div className='paraStyle'>
          {t('tomat')} <br />
        </div>
      </main>
      <Footer />
    </>
  );
}
